print("hello world")
print("hello universe")
print("abd","bfg","htg")
print("abd","bfg","htg", sep='-')
print("abd","bfg","htg", sep='*')
print("abd","bfg","htg", end= "__")
print("abd","bfg","htg", end="   ")
print("abd","bfg","htg", sep='-')